### ISSUE TITLE
GGUF加载模型的精度只支持 'F16', 'Q4_0' ， 但所使用 Q4_0 模型的 output.weight 不是 Q4_0 或者 FP16

### ISSUE THREAD

**Issue by Morxi** [airockchip/rknn-llm#100]
问题描述：
尝试下载 https://huggingface.co/Qwen/Qwen2.5-3B-Instruct-GGUF/blob/main/qwen2.5-3b-instruct-q4_0.gguf 并转换用于推理
```python
modelpath = 'rknn-llm/qwen2.5-3b-instruct-q4_0.gguf'
ret = llm.load_gguf(model = modelpath)
```

报错如下：
```shell
$ python test.py 
INFO: rkllm-toolkit version: 1.1.0
ERROR: Found unsupported GGMLQuantizationType: output.weight -> Q6_K! we only support these types: ['F16', 'Q4_0']!
```

一开始以为是文件下错了或者Huggingface下错了，然后使用HF的在线Metadata功能确认了一下，发现确实output.weight是Q6_K
![image](https://github.com/user-attachments/assets/9d5bdc99-41ea-4e94-a2ee-3999d756264d)

于是我试了一下其他的模型，暂时还没发现使用的GGUF Q4_0模型里面输出为F16或者Q4_0,基本上都是 F32 或者其他的精度

我目前先选择使用加载Huggingface模型的方法转换模型

**Comment by waydong** [comment]
hi，转q4_0时候，设置下不量化output.weight，命令如下：
./build/bin/llama-quantize --leave-output-tensor --token-embedding-type f16 model_f16.gguf q4_0
