### ISSUE TITLE
Request for a Python 3.10 Wheel File

### ISSUE THREAD

**Issue by FUjr** [airockchip/rknn-llm#102]
I am currently using Google Colab, which provides Python version 3.10. Unfortunately, I am unable to use the wheel file compatible with Python 3.8.

If the restriction to Python 3.8 is due to code protection rather than a specific version dependency, would it be possible for you to provide a version of the wheel file compatible with Python 3.10?

**Comment by imkebe** [comment]
BTW... Python 3.8 has reached EoL 10 days ago.... We have now Python 3.13!

**Comment by waydong** [comment]
Hi, we have updated a version of the wheel file compatible with Python 3.10.
