### ISSUE TITLE
rkllm-toolkit version: 1.1.0 Not support MiniCPMV!

### ISSUE THREAD

**Issue by drq123456** [airockchip/rknn-llm#104]
![Uploading 微信图片_20241015144042.png…]()

**Comment by lzz773751548** [comment]
rkllm目前并不直接支持minicpm-v多模态模型，只支持语言模型。
若您想在RK平台部署minicpm-v，可以将在该模型拆分为vit模型和llm。将vit模型转成rknn,将llm转成rkllm,最后部署在RK平台上

**Comment by Ennis12Noble** [comment]
> rkllm目前并不直接支持minicpm-v多模态模型，只支持语言模型。 若您想在RK平台部署minicpm-v，可以将在该模型拆分为vit模型和llm。将vit模型转成rknn,将llm转成rkllm,最后部署在RK平台上

你说的这个方法也有问题，请看https://github.com/airockchip/rknn-llm/issues/101

**Comment by Ennis12Noble** [comment]
@lzz773751548

**Comment by waydong** [comment]
你好，v1.1.2版本已支持导出MiniCPMV中的llm模型。
