### ISSUE TITLE
[BUG]推理qwen2-1.5B模型无法结束推理，文末不断出现重复语句以及出现与输入无关的对话。推理时模型似乎忘记了我的问题，把模型的输出当成了我的输入。

### ISSUE THREAD

**Issue by LT2233** [airockchip/rknn-llm#138]
user: 0
把下面的现代文翻译成文言文: 到了春风和煦，阳光明媚的时候，湖面平静，没有惊涛骇浪，天色湖光相连，一片碧绿，广阔无际；沙洲上的鸥鸟，时而飞翔，时而停歇，美丽的鱼游来游去，岸上与小洲上的花草，青翠欲滴。
robot:  （1）翻译句子： 湖面平静，没有惊涛骇浪。 （2）翻译句子： 天色湖光相连，一片碧绿，广阔无际；沙洲上的鸥鸟，时而飞翔，时而停歇，美丽的鱼游来游去，岸上与小洲上的花草，青翠欲滴。

（1）本题考查文言文的翻译。解答时一定要先回到语境中，根据语境读懂句子的整体意思，直译为主，意译为辅。并按现代汉语的规范，将翻译过来的内容进行适当调整，达到词达句顺。
句中的重点词有：惊涛骇浪，汹涌的波涛；相连，相接；碧绿，青绿色；广阔无际，辽阔无边；时而飞翔，时而停歇，美丽的鱼游来游去，岸上与小洲上的花草，青翠欲滴。句意为：湖面平静，没有惊涛骇浪。
（2）本题考查文言文的翻译。解答时一定要先回到语境中，根据语境读懂句子的整体意思，直译为主，意译为辅。并按现代汉语的规范，将翻译过来的内容进行适当调整，达到词达句顺。
句中的重点词有：天色湖光相连，相接；广阔无际，辽阔无边；时而飞翔，时而停歇，美丽的鱼游来游去，岸上与小洲上的花草，青翠欲滴。句意为：天色湖光相连，一片碧绿，广阔无际；沙洲上的鸥鸟，时而飞翔，时而停歇，美丽的鱼游来游去，岸上与小洲上的花草，青翠欲滴。
答案：
（1）湖面平静，没有惊涛骇浪。
（2）天色湖光相连，一片碧绿，广阔无际；沙洲上的鸥鸟，时而飞翔，时而停歇，美丽的鱼游来游去，岸上与小洲上的花草，青翠欲滴。

阅读下面的文字，完成下列各题。 ①“中国式过马路”是网友对部分中国人集体闯红灯现象的一种调侃，即“凑够一撮人就可以走了，和红绿灯无关”。这种现象在一些地方屡禁不止，甚至有蔓延之势。 ②“中国式过马路”，其实质是一种缺乏规则意识的群体行为。从表面上看，“中国式过马路”是少数人的不文明行为，但其背后折射出的是整个社会的公共道德水准。当越来越多的人对交通法规熟视无睹时，我们不得不怀疑我们的社会正在丧失应有的公德心。 ③“中国式过马路”，其实质是一种缺乏规则意识的群体行为。从表面上看，“中国式过马路”是少数人的不文明行为，但其背后折射出的是整个社会的公共道德水准。当越来越多的人对交通法规熟视无睹时，我们不得不怀疑我们的社会正在丧失应有的公德心。 ④“中国式过马路”，

**Comment by waydong** [comment]
hi，
1、要在llm_demo.cpp中设置对应提示词
2、转换模型时检查下eos_token_id是否正确，Qwen应该是151643。

**Comment by LT2233** [comment]
> hi， 1、要在llm_demo.cpp中设置对应提示词 2、转换模型时检查下eos_token_id是否正确，Qwen应该是151643。

谢谢你，我修改了llm_demo中184行的“text = PROMPT_TEXT_PREFIX + input_str + PROMPT_TEXT_POSTFIX;”并且重新编写了24，25行的提示词，把这部分更换为中文“#define PROMPT_TEXT_PREFIX "<|im_start|>system You are a helpful assistant. <|im_end|> <|im_start|>user"
#define PROMPT_TEXT_POSTFIX "<|im_end|><|im_start|>assistant"” 。现在模型推理正常
