### ISSUE TITLE
运行 Qwen_7b 模型，npu 内存分配报错："failed to malloc npu memory, size: 1418407808, flags: 0x2"

### ISSUE THREAD

**Issue by Tang-JingWei** [airockchip/rknn-llm#139]
![image](https://github.com/user-attachments/assets/20dc72f5-5829-437c-b58a-ed175295320e)

已经设置了：`ulimit -n 1024000`

最后，想问问如何获得rk3588的npu内存占用情况？该通过查看什么文件？感谢！

**Comment by waydong** [comment]
hi, 
1、现在版本不用设置ulimit，查询内存占用，cat /proc/PID/status | grep VmHWM就能查到。
2、尝试下RKLLMParam增加如下配置：
    param.extend_param.base_domain_id = 1;

**Comment by Tang-JingWei** [comment]
非常感谢回复！我在 main.c 源文件中加上了 param.extend_param.base_domain_id = 1 ，然后运行之后没有出现 npu 内存分配报错了，但是出现了段错误。。。

![image](https://github.com/user-attachments/assets/8d898314-42dd-4533-899d-1929ba162061)
![image](https://github.com/user-attachments/assets/aefdcec5-fa57-4a04-8f19-53b4a533c4de)

**Comment by Tang-JingWei** [comment]
> hi, 1、现在版本不用设置ulimit，查询内存占用，cat /proc/PID/status | grep VmHWM就能查到。 2、尝试下RKLLMParam增加如下配置： param.extend_param.base_domain_id = 1;

非常感谢回复！我在 main.c 源文件中加上了 param.extend_param.base_domain_id = 1 ，然后运行之后没有出现 npu 内存分配报错了，但是出现了段错误。。。

![image](https://github.com/user-attachments/assets/8d898314-42dd-4533-899d-1929ba162061)
![image](https://github.com/user-attachments/assets/aefdcec5-fa57-4a04-8f19-53b4a533c4de)

**Comment by waydong** [comment]
> > hi, 1、现在版本不用设置ulimit，查询内存占用，cat /proc/PID/status | grep VmHWM就能查到。 2、尝试下RKLLMParam增加如下配置： param.extend_param.base_domain_id = 1;
> 
> 非常感谢回复！我在 main.c 源文件中加上了 param.extend_param.base_domain_id = 1 ，然后运行之后没有出现 npu 内存分配报错了，但是出现了段错误。。。
> 
> ![image](https://private-user-images.githubusercontent.com/51443742/395764855-8d898314-42dd-4533-899d-1929ba162061.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxNjQ0OTIsIm5iZiI6MTczNDE2NDE5MiwicGF0aCI6Ii81MTQ0Mzc0Mi8zOTU3NjQ4NTUtOGQ4OTgzMTQtNDJkZC00NTMzLTg5OWQtMTkyOWJhMTYyMDYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE0VDA4MTYzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjZTYyNGNiYzlmNDM3NTcxYzIxNTQ2NGNkNDVhNWRlZWE1MjE4OTQ5MGJhY2Q1MWMyZTczMzk0NjQxYWY0YTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tsNUm4uFUPsLlrIF8Fq7cPRhak46BAWHKdPuRz13TN0) ![image](https://private-user-images.githubusercontent.com/51443742/395764888-aefdcec5-fa57-4a04-8f19-53b4a533c4de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxNjQ0OTIsIm5iZiI6MTczNDE2NDE5MiwicGF0aCI6Ii81MTQ0Mzc0Mi8zOTU3NjQ4ODgtYWVmZGNlYzUtZmE1Ny00YTA0LThmMTktNTNiNGE1MzNjNGRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE0VDA4MTYzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxMTU3MjZkNjJjMjE4NDc0MTM0YWViYjBmYjkyMWVhZTJjNWQ2OGJkNzQ0Y2ZjNjk3NzI3ZjI5MTQ5OWYxZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Htuzi7wdyfIrt8ZeetE3_WTU-VendZRKIQP3zL6iidg)

重启下设备试试

**Comment by Tang-JingWei** [comment]
> > > hi, 1、现在版本不用设置ulimit，查询内存占用，cat /proc/PID/status | grep VmHWM就能查到。 2、尝试下RKLLMParam增加如下配置： param.extend_param.base_domain_id = 1;
> > 
> > 
> > 非常感谢回复！我在 main.c 源文件中加上了 param.extend_param.base_domain_id = 1 ，然后运行之后没有出现 npu 内存分配报错了，但是出现了段错误。。。
> 
> 重启下设备试试

重启了，但是一样的现象。
![image](https://github.com/user-attachments/assets/4bd11859-64cf-425d-acc9-0536ad14a213)
![image](https://github.com/user-attachments/assets/1a9dd173-c974-495b-8255-4f705fd76dcc)

**Comment by waydong** [comment]
main.cpp代码中的image_embed_len=1536是qwen2-vl-2b的，有改成7b的3584吗，不然可能会段错误。

**Comment by Tang-JingWei** [comment]
> main.cpp代码中的image_embed_len=1536是qwen2-vl-2b的，有改成7b的3584吗，不然可能会段错误。

！非常感谢，问题解决了，就是因为这个。
