### ISSUE TITLE
请问一下，样例中的大模型有没有具体的下载链接

### ISSUE THREAD

**Issue by kaylorchen** [airockchip/rknn-llm#14]
我看到是通义的模型，但是点击去一看，发现里面有多个文件，请问有没有具体一点的例子。只想简单测试一下

**Comment by afox666** [comment]
1. 使用下载hugging_face对应模型仓库里面的所有文件
2. 使用rknn-toolkit转换，输入的模型路径其实是第1步下载的模型仓库所在目录（也就是说要下载所有的文件）
3. 将转换得到的rkllm模型传到开发板上进行推理即可

**Comment by kaylorchen** [comment]
> 1. 下载hugging_face对应模型仓库里面的所有文件
> 2. 使用rknn-toolkit转换，输入的模型路径其实是第1步下载的模型仓库所在目录（也就是说要下载所有的文件）
> 3. 将转换得到的rkllm模型传到开发板上进行推理即可

谢谢。我试试
