### ISSUE TITLE
多模态模型转onnx报错：ValueError: Unsupported ONNX opset version: 18

### ISSUE THREAD

**Issue by skywalkerjc** [airockchip/rknn-llm#142]
执行多模态转换qwen2 vl时，rkllm可以成功转换，但是测试了多种rknn环境，用docker和conda都测试过，均报错，最常见错误为
The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
`Qwen2VLRotaryEmbedding` can now be fully parameterized by passing the model config through the `config` argument. All other arguments will be removed in v4.46
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████| 2/2 [02:37<00:00, 78.93s/it]
Traceback (most recent call last):
  File "export/export_vision.py", line 61, in <module>
    torch.onnx.export(model, pixel_values, "./onnx/qwen2_vl_2b_vision.onnx", opset_version=18)
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/__init__.py", line 316, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 107, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 707, in _export
    _set_opset_version(opset_version)
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/symbolic_helper.py", line 849, in _set_opset_version
    raise ValueError("Unsupported ONNX opset version: " + str(opset_version))
ValueError: Unsupported ONNX opset version: 18

无奈将export/export_vision.py中torch.onnx.export的参数opset_version改为12后，以外终止了

The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
`Qwen2VLRotaryEmbedding` can now be fully parameterized by passing the model config through the `config` argument. All other arguments will be removed in v4.46
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████| 2/2 [02:29<00:00, 74.70s/it]
export/export_vision.py:46: TracerWarning: torch.from_numpy results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  rotary_pos_emb = torch.from_numpy(np.load("./rotary_pos_emb.npy")).to(dtype=hidden_states.dtype, device=hidden_states.device)
export/export_vision.py:47: TracerWarning: torch.from_numpy results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  cu_seqlens = torch.from_numpy(np.load("./cu_seqlens.npy")).to(dtype=torch.int32, device=hidden_states.device)
/usr/local/lib/python3.8/dist-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py:198: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  x1 = x[..., : x.shape[-1] // 2]
/usr/local/lib/python3.8/dist-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py:199: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  x2 = x[..., x.shape[-1] // 2 :]
/usr/local/lib/python3.8/dist-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py:344: TracerWarning: Using len to get tensor shape might cause the trace to be incorrect. Recommended usage would be tensor.shape[0]. Passing a tensor of different shape might lead to errors or silently give incorrect results.
  for i in range(1, len(cu_seqlens)):
Killed

**Comment by skywalkerjc** [comment]
rkllm环境下手装rknn_toolkit2:v2.2.1和用rknn_toolkit2:v2.3.0的docker镜像均会报错或这以外退出，如果可以，请提供详细的软硬件环境要求

**Comment by c0zaut** [comment]
@skywalkerjc 

Your version of torch needs to be upgraded. I had the same error, and was able to clear by adding this to my Dockerfile:
```
RUN python3 -m pip install --upgrade torch pillow
```

Before installing Python dependencies, I would also recommend including the following apt packages: `libgl1-mesa-glx ffmpeg libsm6 libxext6 libjpeg-dev libpng-dev`. Here is the full apt section:

```
SHELL ["/bin/bash", "-exo", "pipefail", "-c"]

RUN echo 'APT::Install-Suggests "0";' >> /etc/apt/apt.conf.d/00-docker \
    && echo 'APT::Install-Recommends "0";' >> /etc/apt/apt.conf.d/00-docker

RUN DEBIAN_FRONTEND=noninteractive \
  apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y python3 pip python3-tk libgl1-mesa-glx ffmpeg libsm6 libxext6 libjpeg-dev libpng-dev \
  && rm -rf /var/lib/apt/lists/*
```

Hopefully that helps! 
I will try to push something to my GitHub later today for an automated conversion pipeline with Qwen2VL, since I was able to get a working implementation. I'm not sure why they decided to go with the older version of rknn toolkit, since I know that 2.2.3 can run on ARM and it also supports accurate Stable Diffusion 1.5 LCM inference (source: https://huggingface.co/happyme531/Stable-Diffusion-1.5-LCM-ONNX-RKNN2 ) Regardless, I'll be using 2.2.1 for the initial version, and once I have a working inference pipeline in my Gradio app, I'll pivot back to experimenting with newer versions.

**Comment by skywalkerjc** [comment]
The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
`Qwen2VLRotaryEmbedding` can now be fully parameterized by passing the model config through the `config` argument. All other arguments will be removed in v4.46
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████| 2/2 [00:44<00:00, 22.41s/it]
export/export_vision.py:46: TracerWarning: torch.from_numpy results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  rotary_pos_emb = torch.from_numpy(np.load("./rotary_pos_emb.npy")).to(dtype=hidden_states.dtype, device=hidden_states.device)
export/export_vision.py:47: TracerWarning: torch.from_numpy results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  cu_seqlens = torch.from_numpy(np.load("./cu_seqlens.npy")).to(dtype=torch.int32, device=hidden_states.device)
/usr/local/lib/python3.8/dist-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py:399: TracerWarning: Using len to get tensor shape might cause the trace to be incorrect. Recommended usage would be tensor.shape[0]. Passing a tensor of different shape might lead to errors or silently give incorrect results.
  for i in range(1, len(cu_seqlens)):
root@45a7dbfb3655:/app/rknn-llm/examples/rkllm_multimodel_demo#

非常感谢指导，opset版本没有报错了，但是在for i in range(1, len(cu_seqlens)):后又终止了，硬件配置不够？onnx导出目录中生成了很多_visual_blocks.9_attn_Constant_x_attr__value这样的文件，没有onnx模型

**Comment by c0zaut** [comment]
As suspected, you are definitely running out of memory. Can you post the output of `free -m` and `df -h`? Converting the 2b model requires using swap on my device with 32gb or RAM.

**Comment by skywalkerjc** [comment]
@c0zaut 应该是的，我物理机只有32G内存，分给docker只有15G，我今天换一台内存大点的电脑再试试

**Comment by c0zaut** [comment]
Good luck! I tweaked their scripts so its all consolidated into a single workflow, if you want to try it out. It includes a CLI selector, and handles downloading the model from Huggingface directly. 
Sorry for the bad README, but I think you are experienced enough with Docker to figure it lol - https://github.com/c0zaut/rkllm-mm-export

**Comment by skywalkerjc** [comment]
呃。。。。我今天加装了内存，给docker分了49g内存，但是还是同样的以外退出了，很奇怪，应该还是环境没装对，我正在用你的镜像试试，希望能成功

**Comment by c0zaut** [comment]
@skywalkerjc are you converting the 2B version?

**Comment by skywalkerjc** [comment]
@c0zaut 你的镜像成功了，完美！我之前也是转的2b，环境几乎一样，所以排除硬件问题，我有空再对比研究下差异在哪里，初步怀疑是pytourch问题，非常感谢

**Comment by c0zaut** [comment]
@skywalkerjc - YAY! Glad it worked! Enjoy and best of luck building something amazing!
