### ISSUE TITLE
chatglm-6b量化报错

### ISSUE THREAD

**Issue by lzjie-tchip** [airockchip/rknn-llm#143]
使用test.py做如下配置：
ret = llm.build(do_quantization=True, optimization_level=1, quantized_dtype='w4a16',
                quantized_algorithm='normal', target_platform='rk3576', num_npu_core=2, extra_qparams=qparams,dataset=dataset)

dataset内容如下：
[{"input":"Human: 你好！\nAssistant: ", "target": "你好！我是人工智能助手KK！"},{"input":"Human: 你可以干什么？\nAssistant: ", "target": "我可以唱跳rap"}]

运行test.py报如下错误：
(RKLLM-Toolkit-1.1.4) root@ea5d57ca8e66:/rkllm/rknn-llm/rkllm-toolkit/examples# python3 test.py 
INFO: rkllm-toolkit version: 1.1.4
WARNING: Setting eos_token is not supported, use the default one.
WARNING: Setting pad_token is not supported, use the default one.
WARNING: Setting unk_token is not supported, use the default one.
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 22.50it/s]
ERROR: Catch exception when loading dataset: _pad() got an unexpected keyword argument 'padding_side'
Build model failed!

如果不选择量化则正常转换，如何才能正确量化？

**Comment by waydong** [comment]
hi,
将tokenization_chatglm.py中ChatGLMTokenizer类的_pad函数加上如下参数可以解决此问题：
padding_side: Optional[int] = None,

**Comment by lzjie-tchip** [comment]
可以了，感谢
