### ISSUE TITLE
Errors found in building kernal.

### ISSUE THREAD

**Issue by sdrzmgy** [airockchip/rknn-llm#16]
Referring the Doc, I tried to build the kernal to fit rkllm toolkit. But there are too many errors.
Firstly, there are too many implicit declaration of function such as 'vm_flags_clear', 'vm_flags_set', 'rockchip_uninit_opp_table' and so on. Above these, i can solve functions like 'vm_flags_clear' and 'vm_flags_set' by adding the declaration myself from raspberry pi. But other functions i cannot find any corresponding functions in the Internet.
Also there are many variables like 'MONITOR_TYPE_DEV' are not undeclared.
Can anybody offer a solution or a built kernal which fit rkllm?
When will these errors be solved?

**Comment by afox666** [comment]
Which board?

**Comment by sdrzmgy** [comment]
> Which board?

Orangepi 5 Plus with RK3588

**Comment by sdrzmgy** [comment]
> Which board?

The kernal source i use is from "https://github.com/orangepi-xunlong/linux-orangepi/tree/orange-pi-5.10-rk3588"

**Comment by afox666** [comment]
I have the same board with you. 
The kernel version I have built is 6.1, and it runs well on my board.

Operate according to the following steps:
1. Run `build.sh`，choose `Full OS image for flashing`,  the whole codes that building needed will be downloaded.
2. Add these code to  kernel/orange-pi-6.1-rk35xx/include/linux/mm.h
``` c

static inline void vm_flags_set(struct vm_area_struct *vma,
                               vm_flags_t flags)
{

       vma->vm_flags |= flags;
}

static inline void vm_flags_clear(struct vm_area_struct *vma,
                                 vm_flags_t flags)
{

       vma->vm_flags &= ~flags;
}
```
3. Modify `userpatches/config-default.conf`, set the value of `IGNORE_UPDATES` to `yes`
4. Copy `drivers/rknpu` dir to `kernel/orange-pi-6.1-rk35xx/drivers`
5. Rerun `build.sh`, choose `Full OS image for flashing`

Before you run the demo of rknn-llm, exec command: `ulimit -u 8192`

**Comment by sdrzmgy** [comment]
> I have the same board with you. The kernel version I have built is 6.1, and it runs well on my board.
> 
> Operate according to the following steps:
> 
> 1. Run `build.sh`，choose `Full OS image for flashing`,  the whole codes that building needed will be downloaded.
> 2. Add these code to `kernel/orange-pi-6.1-rk35xx/include/linux/mm.h`
> 
> ```c
> static inline void vm_flags_set(struct vm_area_struct *vma,
>                                vm_flags_t flags)
> {
> 
>        vma->vm_flags |= flags;
> }
> 
> static inline void vm_flags_clear(struct vm_area_struct *vma,
>                                  vm_flags_t flags)
> {
> 
>        vma->vm_flags &= ~flags;
> }
> ```
> 
> 3. Modify `userpatches/config-default.conf`, set the value of `IGNORE_UPDATES` to `yes`
> 4. Copy `drivers/rknpu` dir to `kernel/orange-pi-6.1-rk35xx/drivers`
> 5. Rerun `build.sh`, choose `Full OS image for flashing`
> 
> Before you run the demo of rknn-llm, exec command: `ulimit -u 8192`

I made it! THANKS a lot!

**Comment by xxxxyu** [comment]
After re-building the kernel, the WiFi module cannot work normally.
I can see the network controller by `lspci`, but `nmcli dev wifi` gives empty output.
Did you guys encounter this?
