### ISSUE TITLE
rkllm_init error

### ISSUE THREAD

**Issue by beingjoey** [airockchip/rknn-llm#17]
init chatglm3-6b model got error output :
gguf_init_from_file: invalid magic characters '���p'

**Comment by fydeos-alex** [comment]
only support LLaMA, Qwen, Qwen2, and Phi-2 now

**Comment by beingjoey** [comment]
try to init qwen1.5-1.8B :
rkllm_init(&llmHandle, param, callback);
E RKNN: [05:45:17.474] failed to convert handle(1020) to fd, ret: -1, errno: 24, errstr: Too many open files

**Comment by fydeos-alex** [comment]
If you are using ssh, try ulimit -n 9999.

**Comment by beingjoey** [comment]
Thanks, it is working now !
