### ISSUE TITLE
run模型时，为什么还需要指定max_context_len?

### ISSUE THREAD

**Issue by AACengineer** [airockchip/rknn-llm#19]
看到User Guide中的案例，为什么在run模型时，还需要设置max_context_len？这个值设置得很小512，和原来模型支持的32k相差很大。
<img width="290" alt="捕获" src="https://github.com/airockchip/rknn-llm/assets/61830993/36889d69-a844-47c7-9ded-09abab14ca29">

**Comment by sdrzmgy** [comment]
这应该是NPU的特性问题，如果这个数很大，推理的时候会很慢。

**Comment by AACengineer** [comment]
max_context_len这个参数，是否意味着推理时prefill阶段的graph中，q/k/v的seq_length都是512？

**Comment by OccamsRazor1** [comment]
不是，会进行分桶处理
