### ISSUE TITLE
E RKNN: [00:13:05.159] failed to convert handle(1020) to fd, ret: -1, errno: 24, errstr: Too many open files

### ISSUE THREAD

**Issue by wmx-github** [airockchip/rknn-llm#43]
我huggingface 模型 Qwen1.5-0.5B-Chat
生成 qwen.rkllm
push到板子上：
`orangepi@orangepi5b:~/workspace/llm$ ls

librkllmrt.so  llm_demo  qwen.rkllm
`
然后
`export LD_LIBRARY_PATH=./

orangepi@orangepi5b:~/workspace/llm$ ./llm_demo ./qwen.rkllm 

rkllm init start
E RKNN: [00:03:36.400] failed to convert handle(1020) to fd, ret: -1, errno: 24, errstr: Too many open files
Segmentation fault (core dumped)

`
怎么解决

**Comment by 80Builder80** [comment]
In terminal 
ulimit -n 10096
