### ISSUE TITLE
rkllm_init error in rkllm1.0.1

### ISSUE THREAD

**Issue by eework** [airockchip/rknn-llm#44]
hw: rock 5b 8G
kernel: 5.10.110
npu driver: 0.9.6

使用llm_demo进行验证的时候，发现报错
![image](https://github.com/airockchip/rknn-llm/assets/43036364/e33fcca6-7af9-45fc-9ed4-0204ed6a24dc)
调试代码发现，是调用rkllm_init的时候出错的，旧版本rkllm也跑起来过，旧版没发现这个问题

**Comment by lzz773751548** [comment]
更新最新的1.0.2 beta可解决该问题

**Comment by eework** [comment]
已经更新验证了，能正常跑起来了，谢谢
