### ISSUE TITLE
RKNN: [22:16:52.189] failed to convert handle(1020) to fd, ret: -1, errno: 24, errstr: Too many open files

### ISSUE THREAD

**Issue by 17656178609** [airockchip/rknn-llm#47]
<img width="771" alt="image" src="https://github.com/airockchip/rknn-llm/assets/53132106/a0362017-14f4-4850-bb1b-5825ef312cee">
运行时报这个错误。

**Comment by lzjie-tchip** [comment]
ulimit -n 102400

**Comment by 17656178609** [comment]
> lzjie

thank you
