### ISSUE TITLE
转化模型时出错

### ISSUE THREAD

**Issue by 17656178609** [airockchip/rknn-llm#52]
我尝试gemma 2B模型，将模型从huggingface下载下来进行转化出现
rkllm-toolkit version: 1.0.1
Error: expected value at line 1 column 1!
Catch exception when loading model!
Load model failed!
这个错误。 这个应该怎么解决

**Comment by Tang-JingWei** [comment]
> 我尝试gemma 2B模型，将模型从huggingface下载下来进行转化出现 rkllm-toolkit version: 1.0.1 Error: expected value at line 1 column 1! Catch exception when loading model! Load model failed! 这个错误。 这个应该怎么解决

你好，请问是怎么解决的呀？我也遇到了相同的问题
