### ISSUE TITLE
是否支持 rk3582 

### ISSUE THREAD

**Issue by walletiger** [airockchip/rknn-llm#59]
运行时报错：
root@rock-5c:/opt/rkllm_server# ./run.sh  Qwen-1_8B-Chat.rkllm
=========init....===========
rkllm-runtime version: 1.0.1

Query platform error!
理论上 rk3582 npu 部分与 rk3588 差异不大，如何解决， 求助！

**Comment by walletiger** [comment]
更新了1.0.2 如下报错:
root@rock-5c:/opt/rkllm_server# ./run.sh Qwen-1_8B-Chat.rkllm
=========init....===========
rkllm-runtime version: 1.0.1, rknpu driver version: 0.9.6, platform: RK3588
E RKNN: [16:36:48.736] Cannot load clGetPlatformIDs!
Error: could find any OpenCL devices!

**Comment by chenpingfromgxu** [comment]
有个地方默认开了GPU改成False就好了。

**Comment by walletiger** [comment]
可以了
