### ISSUE TITLE
internlm2-chat-1_8b模型转换出错

### ISSUE THREAD

**Issue by TRQ-UP** [airockchip/rknn-llm#61]
![1](https://github.com/airockchip/rknn-llm/assets/37291715/0007f8b0-1cba-4e71-9fe4-ba8df0032da3)
转换报错：Error: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data()，serialized.size())]! Catch exception when converting model!
工具版本：rkllm-tookit version：1.0.1

转换代码：
modelpath = '/home/mct/rk-llm/internlm2-chat-1_8b/'
llm = RKLLM()

# Load model
ret = llm.load_huggingface(model=modelpath)
if ret != 0:
    print('Load model failed!')
    exit(ret)

# Build model
ret = llm.build(do_quantization=True,quantized_dtype='w8a8', target_platform='rk3588')
if ret != 0:
    print('Build model failed!')
    exit(ret)

# Export rknn model
ret = llm.export_rkllm("./internlm2.rkllm")
if ret != 0:
    print('Export model failed!')
    exit(ret)

**Comment by waydong** [comment]
hi，请尝试下1.1.0版本，可以解决此问题。
