### ISSUE TITLE
跑大模型遇到问题

### ISSUE THREAD

**Issue by shaqing** [airockchip/rknn-llm#62]
` ./llm_demo  ../../chatglm3-6b-rkllm/chatglm3-6b.rkllm 
rkllm init start
rkllm-runtime version: 1.0.1, rknpu driver version: 0.8.2, platform: RK3588
Warning: Your rknpu driver version is too low, please upgrade to 0.9.6.
E RKNN: [10:48:59.683] failed to allocate handle, ret: -1, errno: 12, errstr: Cannot allocate memory

can not create weight memory for domain1
E RKNN: [10:49:00.480] failed to allocate handle, ret: -1, errno: 12, errstr: Cannot allocate memory

can not create weight memory for domain2
E RKNN: [10:49:05.216] failed to convert handle(1020) to fd, ret: -1, errno: 24, errstr: Too many open files
E RKNN: [10:49:05.216] failed to malloc npu memory, size: 80, flags: 0xa
E RKNN: [10:49:05.216] failed to convert handle(1021) to fd, ret: -1, errno: 24, errstr: Too many open files
E RKNN: [10:49:05.216] failed to malloc npu memory, size: 1792, flags: 0x2
E RKNN: [10:49:05.216] failed to convert handle(1022) to fd, ret: -1, errno: 24, errstr: Too many open files
E RKNN: [10:49:05.216] failed to malloc npu memory, size: 80, flags: 0xa
E RKNN: [10:49:05.216] failed to convert handle(1023) to fd, ret: -1, errno: 24, errstr: Too many open files
E RKNN: [10:49:05.216] failed to malloc npu memory, size: 2048, flags: 0x2
E RKNN: [10:49:05.216] failed to convert handle(1024) to fd, ret: -1, errno: 24, errstr: Too many open files
E RKNN: [10:49:05.216] failed to malloc npu memory, size: 160, flags: 0xa
E RKNN: [10:49:05.217] failed to convert handle(1025) to fd, ret: -1, errno: 24, errstr: Too many open files
E RKNN: [10:49:05.217] failed to malloc npu memory, size: 2560, flags: 0x2
E RKNN: [10:49:05.217] failed to convert handle(1026) to fd, ret: -1, errno: 24, errstr: Too many open files
E RKNN: [10:49:05.217] failed to malloc npu memory, size: 320, flags: 0xa
E RKNN: [10:49:05.217] failed to convert handle(1027) to fd, ret: -1, errno: 24, errstr: Too many open files
E RKNN: [10:49:05.217] failed to malloc npu memory, size: 3584, flags: 0x2
E RKNN: [10:49:05.217] failed to convert handle(1028) to fd, ret: -1, errno: 24, errstr: Too many open files
E RKNN: [10:49:05.217] failed to malloc npu memory, size: 640, flags: 0xa
E RKNN: [10:49:05.217] failed to convert handle(1029) to fd, ret: -1, errno: 24, errstr: Too many open files
E RKNN: [10:49:05.217] failed to malloc npu memory, size: 5632, flags: 0x2
E RKNN: [10:49:05.217] failed to convert handle(1030) to fd, ret: -1, errno: 24, errstr: Too many open files
E RKNN: [10:49:05.217] failed to malloc npu memory, size: 1280, flags: 0xa
E RKNN: [10:49:05.384] failed to convert handle(1031) to fd, ret: -1, errno: 24, errstr: Too many open files
E RKNN: [10:49:05.384] failed to malloc npu memory, size: 1984, flags: 0x2
E RKNN: [10:49:05.384] failed to convert handle(1032) to fd, ret: -1, errno: 24, errstr: Too many open files
E RKNN: [10:49:05.384] failed to malloc npu memory, size: 80, flags: 0xa
E RKNN: [10:49:05.384] failed to convert handle(1033) to fd, ret: -1, errno: 24, errstr: Too many open files
E RKNN: [10:49:05.384] failed to malloc npu memory, size: 2048, flags: 0x2
E RKNN: [10:49:05.384] failed to convert handle(1034) to fd, ret: -1, errno: 24, errstr: Too many open files
E RKNN: [10:49:05.384] failed to malloc npu memory, size: 120, flags: 0xa
E RKNN: [10:49:05.384] failed to convert handle(1035) to fd, ret: -1, errno: 24, errstr: Too many open files
E RKNN: [10:49:05.384] failed to malloc npu memory, size: 2560, flags: 0x2
E RKNN: [10:49:05.384] failed to convert handle(1036) to fd, ret: -1, errno: 24, errstr: Too many open files
E RKNN: [10:49:05.384] failed to malloc npu memory, size: 200, flags: 0xa
E RKNN: [10:49:05.384] failed to convert handle(1037) to fd, ret: -1, errno: 24, errstr: Too many open files
E RKNN: [10:49:05.384] failed to malloc npu memory, size: 3008, flags: 0x2
E RKNN: [10:49:05.384] failed to convert handle(1038) to fd, ret: -1, errno: 24, errstr: Too many open files
E RKNN: [10:49:05.384] failed to malloc npu memory, size: 320, flags: 0xa
E RKNN: [10:49:05.384] failed to convert handle(1039) to fd, ret: -1, errno: 24, errstr: Too many open files
E RKNN: [10:49:05.384] failed to malloc npu memory, size: 3904, flags: 0x2
E RKNN: [10:49:05.384] failed to convert handle(1040) to fd, ret: -1, errno: 24, errstr: Too many open files
E RKNN: [10:49:05.384] failed to malloc npu memory, size: 600, flags: 0xa
E RKNN: [10:49:05.384] failed to convert handle(1041) to fd, ret: -1, errno: 24, errstr: Too many open files
E RKNN: [10:49:05.384] failed to malloc npu memory, size: 5696, flags: 0x2
E RKNN: [10:49:05.384] failed to convert handle(1042) to fd, ret: -1, errno: 24, errstr: Too many open files
E RKNN: [10:49:05.384] failed to malloc npu memory, size: 1160, flags: 0xa
E RKNN: [10:49:05.384] failed to convert handle(1043) to fd, ret: -1, errno: 24, errstr: Too many open files
E RKNN: [10:49:05.384] failed to malloc npu memory, size: 9280, flags: 0x2
E RKNN: [10:49:05.384] failed to convert handle(1044) to fd, ret: -1, errno: 24, errstr: Too many open files
E RKNN: [10:49:05.384] failed to malloc npu memory, size: 2280, flags: 0xa
E RKNN: [10:49:05.387] failed to convert handle(1045) to fd, ret: -1, errno: 24, errstr: Too many open files
E RKNN: [10:49:05.387] failed to malloc npu memory, size: 2818048, flags: 0x2
GGML_ASSERT:ret == `
跑大模型时，遇到的问题，请问如何解决呢？

**Comment by shaqing** [comment]
解决方案:ulimit -n 102400

**Comment by leezpeng** [comment]
> 解决方案:ulimit -n 102400

哇！真的有用 非常感谢！

**Comment by wpx-1** [comment]
> 解决方案:ulimit -n 102400

牛牛牛，我也解决啦。感谢大佬
