### ISSUE TITLE
Error: iommu_context->weight_memory is NULL

### ISSUE THREAD

**Issue by meanshe** [airockchip/rknn-llm#68]
./llm_demo /home/llm_model/chatglm3-6b-32k.rkllm
rkllm init start
rkllm-runtime version: 1.0.1, rknpu driver version: 0.9.6, platform: RK3588
E RKNN: [15:47:03.156] failed to allocate handle, ret: -1, errno: 14, errstr: Bad address

can not create weight memory for domain1
E RKNN: [15:47:04.079] failed to allocate handle, ret: -1, errno: 14, errstr: Bad address

can not create weight memory for domain2
Error: iommu_context->weight_memory is NULL
Segmentation fault

**Comment by waydong** [comment]
Hi, please update to the latest toolchain and drivers to resolve this issue
