### ISSUE TITLE
What is the cause of process interruption during model conversion？

### ISSUE THREAD

**Issue by Han-WG** [airockchip/rknn-llm#7]
![Screenshot from 2024-03-27 17-02-24](https://github.com/airockchip/rknn-llm/assets/45985213/9d8e5536-1e7e-4337-8ba6-fae57888f830)
system memory : 64GB
IDEA memory : 16GB
model name : LLaMA-7b

**Comment by Han-WG** [comment]
code :
`from rkllm.api import RKLLM

modelpath = .../llama-1'
llm = RKLLM()

# Load model
ret = llm.load_huggingface(model=modelpath)
if ret != 0:
    print('Load model failed!')
    exit(ret)

# Build model
ret = llm.build(do_quantization=True, optimization_level=1, quantized_dtype='w8a8', target_platform='rk3588')
if ret != 0:
    print('Build model failed!')
    exit(ret)

# Export rknn model
ret = llm.export_rkllm("./llama-7b.rkllm")
if ret != 0:
    print('Export model failed!')
    exit(ret)`

**Comment by noah003** [comment]
Hi, have you been able to successfully convert the model? @Han-WG
