### ISSUE TITLE
recommend rkllm_run interface include a version that can directly accept embeddings.，建议rkllm_run接口有能直接接受embedding的版本

### ISSUE THREAD

**Issue by shiyu-ren** [airockchip/rknn-llm#76]
Currently, rkllm_run only accepts strings, and its internal inference process is too much of a black box, making it impossible to extend to multimodal model inference. It is recommended to offer a version that accepts embedding vectors for inference.

rkllm_run目前只接受string，内部的推理太过于黑盒，无法扩展到多模态模型的推理，建议可以开放一个接受embedding向量进行推理的版本。

**Comment by vincenzodentamaro** [comment]
I agree. In order to build a vector database, we need embeddings. How can we extract embeddings from rkllm?

**Comment by hebangwen** [comment]
It appears that they are in the process of developing the API, but it is not currently available to regular users.

**Comment by waydong** [comment]
你好，目前已经支持embedding输入推理。
