### ISSUE TITLE
ERROR: rkllm_toolkit-1.0.1-cp38-cp38-linux_x86_64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by redwolf2019** [airockchip/rknn-llm#81]
how to run script: ``` pip3 install packages/rkllm_toolkit-1.0.1-cp38-cp38-linux_x86_64.whl ```

**Comment by cselover** [comment]
My issue is ‘ERROR: rkllm_toolkit-1.1.4-cp38-cp38-linux_x86_64.whl is not a supported wheel on this platform.’,is this the same as yours? So how do you solve this

**Comment by c0zaut** [comment]
You have to install it on x86_64 architecture - the package is only for converting models, and it uses rknn-toolki2 2.2.1b, which doesn't support conversion on ARM.
