### ISSUE TITLE
How do I install on rk3588 which is aarch64 and not x86_64?

### ISSUE THREAD

**Issue by mrodriguez3313** [airockchip/rknn-llm#84]
I get this error when trying to install the .whl file. How to get past this if the device is aarch64?
<img width="990" alt="Screenshot 2024-08-01 at 10 39 39 PM" src="https://github.com/user-attachments/assets/c7cc5998-6045-4d1a-88aa-868e4125cb22">

**Comment by waydong** [comment]
Currently, the rkllm-toolkit is only supported to run on x86 architecture linux systems.

**Comment by Todayonlymyself** [comment]
When will support for AArch architecture deployment be available?
