### ISSUE TITLE
转换模型时导出失败 / Model Export Failed During Conversion

### ISSUE THREAD

**Issue by CallMeMushroom** [airockchip/rknn-llm#98]
在转换 Qwen1.5-0.5B（这是最小的模型）时，已经转换成功、但导出模型时失败，提示空间不足。  
When converting Qwen1.5-0.5B (the smallest model), the conversion was successful, but the export failed with an error indicating insufficient space.  
```
INFO: rkllm-toolkit version: 1.0.2b6
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
Building model: 100%|████████████████████████████████████████████████████████████████| 342/342 [00:03<00:00, 94.98it/s]
Converting model: 100%|█████████████████████████████████████████████████████████| 291/291 [00:00<00:00, 1928187.15it/s]
ERROR: Catch exception when converting model: Not enough free space to write 156797952 bytes
Export model failed!
```

实际空间是足够的  
There is actually enough space.  
```
Filesystem      Size  Used Avail Use% Mounted on
...
/dev/vdb        2.0T  1.2T  857G  59% /data
...
```

内存也十分充足  
Memory is also sufficient.  
```
              total        used        free      shared  buff/cache   available
Mem:            62G         18G         22G        3.1G         22G         40G
Swap:            0B          0B          0B
```

整个转换代码如下：  
The complete conversion code is as follows:  
```python
from rkllm.api import RKLLM

rkllm = RKLLM()

# Load model
# Use 'export CUDA_VISIBLE_DEVICES=2' to specify GPU device
ret = rkllm.load_huggingface(model='/data/llm-on-device/Qwen1.5-0.5B', device='cpu') # options ['cpu', 'cuda']
if ret != 0:
    print('Load model failed!')
    exit(ret)

# Build model
ret = rkllm.build(do_quantization=True, optimization_level=0, quantized_dtype='w8a8',
                  target_platform='rk3588')
if ret != 0:
    print('Build model failed!')
    exit(ret)

# Export rkllm model
ret = rkllm.export_rkllm(export_path='/data/llm-on-device/Qwen1.5-0.5B.rkllm')
if ret != 0:
    print('Export model failed!')
    exit(ret)
```

为什么会转换失败呢？正确的转换操作是怎样的？
Why did the conversion fail? What is the correct way to perform the conversion?

**Comment by waydong** [comment]
可以尝试下1.1.0版本，并确认模型导出的路径是否有写入权限。

**Comment by 2833034152** [comment]
请问这个问题怎么解决的，我现在系统、磁盘空间也是充足的，同样报错：

python export_deepseek_1.5b_rkllm.py 
/root/autodl-tmp/miniconda3/envs/py3.10_rk_llm/lib/python3.10/site-packages/rkllm/api/rkllm.py:5: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  self.base = RKLLMBase(v)
INFO: rkllm-toolkit version: 1.2.3
Building model: 100%|██████████████████████████████████████████| 371/371 [00:14<00:00, 25.44it/s]
Optimizing model: 100%|██████████████████████████████████████████| 28/28 [00:32<00:00,  1.15s/it]
WARNING: The bos token has two ids: 151646 and 151643, please ensure that the bos token ids in config.json and tokenizer_config.json are consistent!
INFO: Setting token_id of bos to 151646
INFO: Setting token_id of eos to 151643
INFO: Setting add_bos_token to True
INFO: Setting add_eos_token to False
Converting model: 100%|███████████████████████████████████| 339/339 [00:00<00:00, 1947765.83it/s]
ERROR: Catch exception when converting model: Not enough free space to write 77807616 bytes
Export model failed!

**Comment by xtfan** [comment]
@2833034152 你好，模型导出报磁盘空间不够的问题解决了么？请问是怎么解决的？

**Comment by waydong** [comment]
> [@2833034152](https://github.com/2833034152) 你好，模型导出报磁盘空间不够的问题解决了么？请问是怎么解决的？

你的rkllm-toolkit是安装在哪个目录，检查下那个目录空间剩余多少

**Comment by xtfan** [comment]
@waydong 你好，目前还有260 GB的空间，却报空间不够，请问我该怎么进一步排查可能的问题？

**Comment by xtfan** [comment]
<img width="3308" height="498" alt="Image" src="https://github.com/user-attachments/assets/a7ecc01e-dc5d-46d9-8ba6-60194e19228f" />

**Comment by waydong** [comment]
导出模型时候会在对应的conda环境包目录下缓存文件，检查下能否正常写入。

**Comment by tttkkkqqq** [comment]
> 导出模型时候会在对应的conda环境包目录下缓存文件，检查下能否正常写入。

@waydong 
我是在容器中跑的，并且可以确定环境包下是可以用root权限写入的
<img width="3324" height="466" alt="Image" src="https://github.com/user-attachments/assets/5411e28a-1cc4-413c-b7ad-ec562eda829e" />
